title: L.J.'s Blog
email: ikocos.au@gmail.com
author: L.J.
description: >-
  Every day is different. new and improved.
baseurl: /daily
url: sinikami.github.io
twitter_username: lovejie2002
github_username: sinikami
markdown: kramdown
show_downloads: true
google_analytics: UA-33641523-1
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_admin

bootstrap:
  assets: true
paginate:  10
paginate_path: "/page:num/" 